soptions:
  formatter: table
  merge-default-rules: true
files:
  include: 'app/styles/**/*.s+(a|c)ss'
  ignore:
    # these are disabled due to bug: https://github.com/sasstools/sass-lint/issues/837
    - 'app/styles/modules/_component.buttons.scss'
    - 'app/styles/modules/_component.table.scss'
    # these are disabled due to lack of granularity in the rule: https://github.com/sasstools/sass-lint/blob/develop/docs/rules/no-color-literals.md
    - 'app/styles/config/_settings.colors.scss'
rules:
  # Extends
  extends-before-mixins: 0
  extends-before-declarations: 2
  placeholder-in-extend: 0

  # Mixins
  mixins-before-declarations: 2

  # Line Spacing
  one-declaration-per-line: 2
  empty-line-between-blocks: 2
  single-line-per-selector: 2

  # Disallows
  no-color-keywords: 2
  no-color-literals: 2
  no-css-comments: 0
  no-debug: 0
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 2
  no-important: 0
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
  no-qualifying-elements: 0
  no-trailing-zero: 2
  no-transition-all: 2
  no-url-protocols: 2
  no-vendor-prefixes: 0
  no-warn: 0
  property-units: 0
  pseudo-element: 0

  # Nesting
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0

  # Name Formats
  class-name-format:
    - 2
    - convention: hyphenatedlowercase
    - allow-leading-underscore: false

  function-name-format:
    - 2
    - convention: snakecase
    - allow-leading-underscore: false

  id-name-format:
    - 2
    - convention: hyphenatedlowercase
    - allow-leading-underscore: false

  mixin-name-format:
    - 2
    - convention: hyphenatedlowercase
    - allow-leading-underscore: false

  placeholder-name-format:
    - 2
    - convention: hyphenatedlowercase
    - allow-leading-underscore: false

  variable-name-format:
    - 2
    - convention: hyphenatedlowercase
    - allow-leading-underscore: false

  # Style Guide
  border-zero: 2
  brace-style:
    - 2
    - style: 1tbs
    - allow-single-line: true
  clean-import-paths:
    - 2
    - leading-underscore: false
    - filename-extension: false
  empty-args: 2
  hex-length: 1
  hex-notation: 2
  indentation:
    - 2
    - size: 4
  leading-zero:
    - 2
    - include: true
  nesting-depth:
    - 2
    - max-depth: 3
  property-sort-order:
    - 1
    - order: smacss
  quotes: 2
  shorthand-values: 1
  url-quotes: 2
  variable-for-property: 2
  zero-unit: 2

  # Inner Spacing
  space-after-comma: 2
  space-before-colon: 2
  space-after-colon: 2
  space-before-brace: 2
  space-before-bang: 2
  space-after-bang: 2
  space-between-parens: 2
  space-around-operator: 2

  # Final Items
  trailing-semicolon: 2
  final-newline: 2
